### ISSUE TITLE
Unable to load NumSharp.Lite with .NET Framework 

### ISSUE THREAD

**Issue by Superpiffer** [SciSharp/NumSharp.Lite#1]
I have a .NET Framework v4.8 project and if I add as reference TensorFlow.NET v0.15.0 and NumSharp.Lite v0.1.4, I can compile correctly but I have this runtime error:

> FileLoadException: Could not load file or assembly 'NumSharp.Lite, Version=0.1.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

After some digging I figured that NumSharp.Lite has "null" PublicKeyToken, because [here](https://github.com/SciSharp/NumSharp.Lite/blob/master/NumSharp/NumSharp.Lite.csproj#L36) the assembly signing is disabled. 
For some reason with a .NET Core application I can run it correctly, but I need it to work with Framework.
Is it possible to sign also this assembly? NumSharp.Core has the key.
Thanks.

EDIT: ok, the problem is not there because of the "Publish" PropertyGroup, but the dll from nuget package still don't have a key:
![image](https://user-images.githubusercontent.com/1334453/75688238-70c90880-5c9f-11ea-8336-421a5460059a.png)

**Comment by Oceania2018** [comment]
Oh, I'll check this issue and update the package if needed. Thank you for pointing out this.

**Comment by Oceania2018** [comment]
Please check the 0.1.5 https://www.nuget.org/packages/NumSharp.Lite/0.1.5
